### PR TITLE
native.scp_send: don't try to recreate remote dir if don't have sftp

### LINKED ISSUE #157: pssh.clients.native.single:scp_send requires sftp when not necessary i.e. when the remote directory exists
https://github.com/ParallelSSH/parallel-ssh/blob/379b8713fa79592b7e45ee4c9b8715efa36e525e/pssh/clients/native/single.py#L775

^ There we are checking if we're copying to a directory, however in the case that we're copying to a remote directory but that directory already exists - we will unnecessarily require sftp.

To work around this we need to use the private `_scp_send` method as when working with for example dropbear you don't have sftp (but of course the scp still works just fine as no remote dir needs to be created).

What might be a solution here? Just try, and create the sftp (or fail in the case the the remote sshd doesn't support it) in the case the directory creation was required?

### PR DESCRIPTION
**Pull request by timsampsoncujo**
This should fix #157 I think

### CODE REVIEW

**Comment by pkittenis** [comment]
Looks good, thanks. Needs a short test though. See [existing scp_send test](https://github.com/ParallelSSH/parallel-ssh/blob/master/tests/test_native_parallel_client.py#L1297).

**Comment by timsampsoncujo** [comment]
Cool. I'll look into it. Cheers

**Comment by cpeel** [comment]
We are needing this fix to allow parallel-ssh to scp files to a system with sftp disabled.

@timsampsoncujo - how can I help get this in? I can add the necessary tests either in your branch or push up a new MR with your changes and the test - please advise.

**Comment by timsampsoncujo** [comment]
@cpeel we abandoned parallel-ssh so be my guest to close this PR, cherry-pick whatever commits here or whatever.

**Comment by cpeel** [comment]
@timsampsoncujo - got it, thanks.

Maintainers: then I suggest you close this PR and go with https://github.com/ParallelSSH/parallel-ssh/pull/188 instead as that one pulls in this commit plus tests.

**Comment by pkittenis** [comment]
Continued in #188

**Pull request closed without merging**
