### PR TITLE
Create server_upgrade.py

### PR DESCRIPTION
**Pull request by midhlajvs**
Used to update the hypervisors using the server list and command list file.

### CODE REVIEW

**Comment by pkittenis** [comment]
Hi, thank you for contributing.

A couple points:

* The syntax and format of the two input files is not shown. Can some sample files be provided, or alternatively make the code take two lists for host and command list respectively and generate those from files.
* Is it intentional that each command is run sequentially?

Code comments in line.

**Comment by midhlajvs** [comment]
Hi, 

I made the suggested changes on the code, hosts and commands are loaded from the file as a list.  It is deliberate to run the commands sequentially.

**Comment by pkittenis** [comment]
Thanks, comments look great.

Can you review the [in code comment about the print statement](https://github.com/ParallelSSH/parallel-ssh/pull/81/files/769edb36147236525787f3a8ea6a54539a0d6d01#diff-c1fe850333827133ab33cd65a946e13d).

Getting syntax error on python 2 with the current code.

**Comment by pkittenis** [comment]
Moved to [wiki](https://github.com/ParallelSSH/parallel-ssh/wiki/Server-Upgrades)

**Pull request closed without merging**
